Feature/al 44 raw send and receive
neonode-inc/zforce-arduino pull request #63
Opened 2023-01-16 11:01 UTC by stesmi

2023-01-16 15:34 UTC, twarenius requested changes

2023-01-16 15:34 UTC, twarenius commented on src/Zforce.cpp
> +      this->remainingRawLength -= asn1PayloadLength;
Where is `asn1PayloadLength` coming from? It doesn't compile without it.

2023-01-16 18:16 UTC, stesmi commented on src/Zforce.cpp
> +      this->remainingRawLength -= asn1PayloadLength;
Had renamed it, and forgot to change that.

2023-01-17 08:21 UTC, twarenius requested changes

2023-01-17 08:21 UTC, twarenius commented on src/Zforce.cpp
> +      uint16_t fullAsn1MessageLength = asn1AfterHeaderLength + asn1HeaderLength
It still doesn't compile. One might think the Arduino GCC compiler is picky but it is missing a semicolon.

2023-01-17 13:07 UTC, twarenius approved these changes, later dismissed
Looks good. I have test run both the SendRaw and ReceiveRaw methods and they both seem to work fine though I haven't been able to produce a scenario for testing the ReceiveRaw method with a large enough ASN.1 response to require multiple invocations.

2023-01-18 08:49 UTC, stesmi commented
> 

I don't like it, either. That means we need to check the code even better than if we could test it.

2023-01-18 10:24 UTC, braide approved these changes

2023-01-18 12:33 UTC, twarenius approved these changes
I have test run the latest changes now and it works as expected. Worth noting though that the case where the ASN.1 payload exceeds the I2C payload size has not been tested.

2023-01-18 12:36 UTC, merged